apiVersion: v1
kind: Namespace
metadata:
  name: test-scaling

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: test-scaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 80 